### ISSUE TITLE
Bulk Processed Files - dealing with duplicate periods across years

### ISSUE THREAD

**Issue by klo9klo9kloi** [jdechalendar/gridemissions#30]
When looking at e.g. `EIA930_2019_Jan_Jun_co2.csv`,  the `period` starts a few hours after `2019-01-01 00:00:00` rather than at the mark, which I'm guessing has something to do with UTC shifting.

Keeping that example file, if I then look at `EIA930_2018_Jul_Dec_co2.csv`, the `period` also overflows into year `2019` for a few hours, such that if I concatenate these two files then there are some duplicate periods.

If I am aggregating emissions by year, what is the proper way to deal with these duplicate `period` rows? Aggregate? Take the one from the latest year?

**Comment by jdechalendar** [comment]
Did you check if the raw EIA files also had this overlap?

How many hours of overlap are you seeing?

I _think_ this code should be working with UTC only in the internals and only converting for exports/plotting.

**Comment by klo9klo9kloi** [comment]
Sifting through the bulk processed files again, it looks like it is always `20XX-01-01 06:00:00` `20XX-01-01 07:00:00` `20XX-01-01 08:00:00`, `20XX-07-01 05:00:00` `20XX-07-01 06:00:00` `20XX-07-01 07:00:00` that overlap between neighboring files

I just checked the raw EIA files and they do not have this problem, the next file always just picks up at the next hour

**Comment by jdechalendar** [comment]
I had a bit of time to look more into this. I don't think this has to do with UTC shifting but with how the EIA are packaging data.

Here is what I observe in the July-December 2018 Balance file
- The last row of CISO data is for midnight on December 31st, 2018 **in local time**, or 8am on Jan 1st, 2019 **in UTC time**
- The last row of MISO data is for midnight on December 31st, 2018 **in local time**, or 5am on Jan 1st, 2019 **in UTC time**

Here is what I observe in the January-June 2019 Balance file
- The first row of CISO data is for 1am on Jan 1st, 2019 **in local time**, or 9am on Jan 1st, 2019 **in UTC time**
- The first row of MISO data is for 1am on Jan 1st, 2019 **in local time**, or 6am on Jan 1st, 2019 **in UTC time**

In the workflows for this package, we compute reconciled electricity data and consumption-based emissions for each timestamp. In the first file, we were treating the hours from 5am to 8am as missing for MISO, and similarly for CISO in the second file for the hours from 6am to 9am.

The short-term solution I am planning here is to load the entire raw dataset in memory, re-partition based on UTC timestamps, and then run the rest of the workflow.

**Comment by klo9klo9kloi** [comment]
Thank you so much for addressing this! 

Could you confirm whether you updated `processed.tar.gz` after your PR? I just downloaded it and loaded the data again, I am still seeing duplicate periods with different Demand values when I load both `EIA930_2018_Jul_Dec_co2.csv` and `EIA930_2019_Jan_Jun_co2.csv`

**Comment by jdechalendar** [comment]
Where are you getting the archive? Another change I made in the same PR is to add a version number to the archive to make it easier to track. The current one should be `processed.0.1.10.dev0.tar.gz`, available [here](https://gridemissions.s3.us-east-2.amazonaws.com/). The link at [this website](https://gridemissions.jdechalendar.su.domains/#/code) was also updated.

I left the old `processed.tar.gz` on the S3 bucket, so maybe that is what you are retrieving?

For the current archive, this is what I see

<img width="929" alt="image" src="https://github.com/user-attachments/assets/26d97cb7-e18b-44a4-a539-e5952851d4c5">

**Comment by klo9klo9kloi** [comment]
Ah! That must be it, thank you! I didn't notice that part of the PR.

In addition to versioned archives, would it also be possible to make a `latest` tagged archive that gets updated each new version?

**Comment by jdechalendar** [comment]
> In addition to versioned archives, would it also be possible to make a `latest` tagged archive that gets updated each new version?

Now available at https://api.gridemissions.com/bulk/latest. I updated the docs [here](https://docs.gridemissions.jdechalendar.su.domains/datasets.html) with a note about this as well
